# Generated by Django 2.1 on 2019-09-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nome')),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('private_key', models.CharField(blank=True, max_length=250, null=True, verbose_name='Chave Privada')),
                ('public_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave Privada')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CarteiraToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=15, null=True)),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
                ('digitos', models.CharField(blank=True, max_length=5, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, max_length=75, null=True)),
                ('id_carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteira.Carteira')),
            ],
        ),
    ]
